### ISSUE TITLE
Can not deserialize instance

### ISSUE THREAD

**Issue by tonymadbrain** [segator/scaleway-sdk#2]
Hello!

We trying to use [this jenkins plugin](https://github.com/jenkinsci/scaleway-cloud-plugin) which require  scaleway-sdk and getting error:
```Mar 14, 2017 2:23:44 PM com.github.segator.jenkins.scaleway.ScalewayCloud provision
WARNING: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: java.io.StringReader@1599b91e; line: 1, column: 5015] (through reference chain: com.github.segator.scaleway.api.entity.ScalewayServersInstances["servers"]->java.util.ArrayList[1]->com.github.segator.scaleway.api.entity.ScalewayServer["extra_networks"]->Object[][0])
com.github.segator.scaleway.api.entity.exceptions.ScalewayException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: java.io.StringReader@1599b91e; line: 1, column: 5015] (through reference chain: com.github.segator.scaleway.api.entity.ScalewayServersInstances["servers"]->java.util.ArrayList[1]->com.github.segator.scaleway.api.entity.ScalewayServer["extra_networks"]->Object[][0])
    at com.github.segator.scaleway.api.ScalewayClient.parseResponse(ScalewayClient.java:284)
    at com.github.segator.scaleway.api.ScalewayClient.getAllServers(ScalewayClient.java:159)
    at com.github.segator.jenkins.scaleway.ScalewayCloud.provision(ScalewayCloud.java:228)
    at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:714)
    at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:320)
    at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:61)
    at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:809)
    at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Can you help?

**Comment by segator** [comment]
Hi, probably Scaleway guys modificate their API, I will set a fix next week, this week I'm so busy.
Thank you

**Comment by segator** [comment]
is fixed
